version: "3.4"
x-api-defaults:
  &api-defaults
  image: milo-api-dev
  ports:
    - "4000:4000"
  environment:
    - NODE_ENV=development
x-app-defaults:
  &app-defaults
  ports:
    - "8081:8081"
  environment:
    - NODE_ENV=development
services:
  api:
    build:
      context: ./api
      dockerfile: dev.dockerfile
    # volume allows us to mount in app code directly into a running container
    # if we update source code, then the changes will take effect immediately
    volumes:
      - "./api/src:/app/src"
    <<: *api-defaults
  apiTest:
    build:
      context: ./api
      dockerfile: dev.dockerfile
      target: dependencies
    <<: *api-defaults
    # note no volume is used for apiTest service, as this is the docker image
    # used in CI, so the full source code must be COPY'd into the image
  app:
    build:
      context: ./app
      dockerfile: dev.dockerfile
      target: dependencies
    image: milo-app-dev
    volumes:
      - "./app:/app"
    <<: *app-defaults
  appTest:
    build:
      context: ./app
      dockerfile: dev.dockerfile
      target: test-dependencies
    image: milo-app-test-dev
    <<: *app-defaults
