version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: dev.dockerfile
    image: milo-dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    # volume allows us to mount in app code directly into a running container
    # if we update source code, then the changes will take effect immediately
    volumes:
      - "./api:/app"
