version: "3.7"
services:
  test:
    build:
      context: ./api
      dockerfile: prod.dockerfile
      target: dependencies
    image: milo-prod
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
  api:
    build:
      context: ./api
      dockerfile: prod.dockerfile
    image: milo-prod
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
