version: "3.4"
x-production:
  &production-defaults
  image: milo-prod
  ports:
    - "4000:4000"
  environment:
    - NODE_ENV=production
services:
  api:
    build:
      context: ./api
      dockerfile: prod.dockerfile
    <<: *production-defaults
  apiTest:
    build:
      context: ./api
      dockerfile: prod.dockerfile
      target: dependencies
    <<: *production-defaults
